CREATE TABLE Source (
    'SourceID' INT,
    'SourceCourt' VARCHAR(192) CHARACTER SET utf8
);
INSERT INTO Source VALUES (1,'U.S. Court of Customs and Patent Appeals');
INSERT INTO Source VALUES (2,'U.S. Court of International Trade');
INSERT INTO Source VALUES (3,'U.S. Court of Claims, Court of Federal Claims');
INSERT INTO Source VALUES (4,'U.S. Court of Military Appeals, renamed as Court of Appeals for the Armed Forces');
INSERT INTO Source VALUES (5,'U.S. Court of Military Review');
INSERT INTO Source VALUES (6,'U.S. Court of Veterans Appeals');
INSERT INTO Source VALUES (7,'U.S. Customs Court');
INSERT INTO Source VALUES (8,'U.S. Court of Appeals, Federal Circuit');
INSERT INTO Source VALUES (9,'U.S. Tax Court');
INSERT INTO Source VALUES (10,'Temporary Emergency U.S. Court of Appeals');
INSERT INTO Source VALUES (12,'U.S. Court for China');
INSERT INTO Source VALUES (13,'U.S. Consular Courts');
INSERT INTO Source VALUES (14,'U.S. Commerce Court');
INSERT INTO Source VALUES (15,'Territorial Supreme Court');
INSERT INTO Source VALUES (16,'Territorial Appellate Court');
INSERT INTO Source VALUES (17,'Territorial Trial Court');
INSERT INTO Source VALUES (18,'Emergency Court of Appeals');
INSERT INTO Source VALUES (19,'Supreme Court of the District of Columbia');
INSERT INTO Source VALUES (20,'Bankruptcy Court');
INSERT INTO Source VALUES (21,'U.S. Court of Appeals, First Circuit');
INSERT INTO Source VALUES (22,'U.S. Court of Appeals, Second Circuit');
INSERT INTO Source VALUES (23,'U.S. Court of Appeals, Third Circuit');
INSERT INTO Source VALUES (24,'U.S. Court of Appeals, Fourth Circuit');
INSERT INTO Source VALUES (25,'U.S. Court of Appeals, Fifth Circuit');
INSERT INTO Source VALUES (26,'U.S. Court of Appeals, Sixth Circuit');
INSERT INTO Source VALUES (27,'U.S. Court of Appeals, Seventh Circuit');
INSERT INTO Source VALUES (28,'U.S. Court of Appeals, Eighth Circuit');
INSERT INTO Source VALUES (29,'U.S. Court of Appeals, Ninth Circuit');
INSERT INTO Source VALUES (30,'U.S. Court of Appeals, Tenth Circuit');
INSERT INTO Source VALUES (31,'U.S. Court of Appeals, Eleventh Circuit');
INSERT INTO Source VALUES (32,'U.S. Court of Appeals, District of Columbia Circuit (includes the Court of Appeals for the District of Columbia but not the District of Columbia Court of Appeals, which has local jurisdiction)');
INSERT INTO Source VALUES (41,'Alabama Middle U.S. District Court');
INSERT INTO Source VALUES (42,'Alabama Northern U.S. District Court');
INSERT INTO Source VALUES (43,'Alabama Southern U.S. District Court');
INSERT INTO Source VALUES (44,'Alaska U.S. District Court');
INSERT INTO Source VALUES (45,'Arizona U.S. District Court');
INSERT INTO Source VALUES (46,'Arkansas Eastern U.S. District Court');
INSERT INTO Source VALUES (47,'Arkansas Western U.S. District Court');
INSERT INTO Source VALUES (48,'California Central U.S. District Court');
INSERT INTO Source VALUES (49,'California Eastern U.S. District Court');
INSERT INTO Source VALUES (50,'California Northern U.S. District Court');
INSERT INTO Source VALUES (51,'California Southern U.S. District Court');
INSERT INTO Source VALUES (52,'Colorado U.S. District Court');
INSERT INTO Source VALUES (53,'Connecticut U.S. District Court');
INSERT INTO Source VALUES (54,'Delaware U.S. District Court');
INSERT INTO Source VALUES (55,'District Of Columbia U.S. District Court');
INSERT INTO Source VALUES (56,'Florida Middle U.S. District Court');
INSERT INTO Source VALUES (57,'Florida Northern U.S. District Court');
INSERT INTO Source VALUES (58,'Florida Southern U.S. District Court');
INSERT INTO Source VALUES (59,'Georgia Middle U.S. District Court');
INSERT INTO Source VALUES (60,'Georgia Northern U.S. District Court');
INSERT INTO Source VALUES (61,'Georgia Southern U.S. District Court');
INSERT INTO Source VALUES (62,'Guam U.S. District Court');
INSERT INTO Source VALUES (63,'Hawaii U.S. District Court');
INSERT INTO Source VALUES (64,'Idaho U.S. District Court');
INSERT INTO Source VALUES (65,'Illinois Central U.S. District Court');
INSERT INTO Source VALUES (66,'Illinois Northern U.S. District Court');
INSERT INTO Source VALUES (67,'Illinois Southern U.S. District Court');
INSERT INTO Source VALUES (68,'Indiana Northern U.S. District Court');
INSERT INTO Source VALUES (69,'Indiana Southern U.S. District Court');
INSERT INTO Source VALUES (70,'Iowa Northern U.S. District Court');
INSERT INTO Source VALUES (71,'Iowa Southern U.S. District Court');
INSERT INTO Source VALUES (72,'Kansas U.S. District Court');
INSERT INTO Source VALUES (73,'Kentucky Eastern U.S. District Court');
INSERT INTO Source VALUES (74,'Kentucky Western U.S. District Court');
INSERT INTO Source VALUES (75,'Louisiana Eastern U.S. District Court');
INSERT INTO Source VALUES (76,'Louisiana Middle U.S. District Court');
INSERT INTO Source VALUES (77,'Louisiana Western U.S. District Court');
INSERT INTO Source VALUES (78,'Maine U.S. District Court');
INSERT INTO Source VALUES (79,'Maryland U.S. District Court');
INSERT INTO Source VALUES (80,'Massachusetts U.S. District Court');
INSERT INTO Source VALUES (81,'Michigan Eastern U.S. District Court');
INSERT INTO Source VALUES (82,'Michigan Western U.S. District Court');
INSERT INTO Source VALUES (83,'Minnesota U.S. District Court');
INSERT INTO Source VALUES (84,'Mississippi Northern U.S. District Court');
INSERT INTO Source VALUES (85,'Mississippi Southern U.S. District Court');
INSERT INTO Source VALUES (86,'Missouri Eastern U.S. District Court');
INSERT INTO Source VALUES (87,'Missouri Western U.S. District Court');
INSERT INTO Source VALUES (88,'Montana U.S. District Court');
INSERT INTO Source VALUES (89,'Nebraska U.S. District Court');
INSERT INTO Source VALUES (90,'Nevada U.S. District Court');
INSERT INTO Source VALUES (91,'New Hampshire U.S. District Court');
INSERT INTO Source VALUES (92,'New Jersey U.S. District Court');
INSERT INTO Source VALUES (93,'New Mexico U.S. District Court');
INSERT INTO Source VALUES (94,'New York Eastern U.S. District Court');
INSERT INTO Source VALUES (95,'New York Northern U.S. District Court');
INSERT INTO Source VALUES (96,'New York Southern U.S. District Court');
INSERT INTO Source VALUES (97,'New York Western U.S. District Court');
INSERT INTO Source VALUES (98,'North Carolina Eastern U.S. District Court');
INSERT INTO Source VALUES (99,'North Carolina Middle U.S. District Court');
INSERT INTO Source VALUES (100,'North Carolina Western U.S. District Court');
INSERT INTO Source VALUES (101,'North Dakota U.S. District Court');
INSERT INTO Source VALUES (102,'Northern Mariana Islands U.S. District Court');
INSERT INTO Source VALUES (103,'Ohio Northern U.S. District Court');
INSERT INTO Source VALUES (104,'Ohio Southern U.S. District Court');
INSERT INTO Source VALUES (105,'Oklahoma Eastern U.S. District Court');
INSERT INTO Source VALUES (106,'Oklahoma Northern U.S. District Court');
INSERT INTO Source VALUES (107,'Oklahoma Western U.S. District Court');
INSERT INTO Source VALUES (108,'Oregon U.S. District Court');
INSERT INTO Source VALUES (109,'Pennsylvania Eastern U.S. District Court');
INSERT INTO Source VALUES (110,'Pennsylvania Middle U.S. District Court');
INSERT INTO Source VALUES (111,'Pennsylvania Western U.S. District Court');
INSERT INTO Source VALUES (112,'Puerto Rico U.S. District Court');
INSERT INTO Source VALUES (113,'Rhode Island U.S. District Court');
INSERT INTO Source VALUES (114,'South Carolina U.S. District Court');
INSERT INTO Source VALUES (115,'South Dakota U.S. District Court');
INSERT INTO Source VALUES (116,'Tennessee Eastern U.S. District Court');
INSERT INTO Source VALUES (117,'Tennessee Middle U.S. District Court');
INSERT INTO Source VALUES (118,'Tennessee Western U.S. District Court');
INSERT INTO Source VALUES (119,'Texas Eastern U.S. District Court');
INSERT INTO Source VALUES (120,'Texas Northern U.S. District Court');
INSERT INTO Source VALUES (121,'Texas Southern U.S. District Court');
INSERT INTO Source VALUES (122,'Texas Western U.S. District Court');
INSERT INTO Source VALUES (123,'Utah U.S. District Court');
INSERT INTO Source VALUES (124,'Vermont U.S. District Court');
INSERT INTO Source VALUES (125,'Virgin Islands U.S. District Court');
INSERT INTO Source VALUES (126,'Virginia Eastern U.S. District Court');
INSERT INTO Source VALUES (127,'Virginia Western U.S. District Court');
INSERT INTO Source VALUES (128,'Washington Eastern U.S. District Court');
INSERT INTO Source VALUES (129,'Washington Western U.S. District Court');
INSERT INTO Source VALUES (130,'West Virginia Northern U.S. District Court');
INSERT INTO Source VALUES (131,'West Virginia Southern U.S. District Court');
INSERT INTO Source VALUES (132,'Wisconsin Eastern U.S. District Court');
INSERT INTO Source VALUES (133,'Wisconsin Western U.S. District Court');
INSERT INTO Source VALUES (134,'Wyoming U.S. District Court');
INSERT INTO Source VALUES (150,'Louisiana U.S. District Court');
INSERT INTO Source VALUES (151,'Washington U.S. District Court');
INSERT INTO Source VALUES (152,'West Virginia U.S. District Court');
INSERT INTO Source VALUES (153,'Illinois Eastern U.S. District Court');
INSERT INTO Source VALUES (155,'South Carolina Eastern U.S. District Court');
INSERT INTO Source VALUES (160,'South Carolina Western U.S. District Court');
INSERT INTO Source VALUES (162,'Alabama U.S. District Court');
INSERT INTO Source VALUES (163,'U.S. District Court for the Canal Zone');
INSERT INTO Source VALUES (164,'Georgia U.S. District Court');
INSERT INTO Source VALUES (165,'Illinois U.S. District Court');
INSERT INTO Source VALUES (166,'Indiana U.S. District Court');
INSERT INTO Source VALUES (167,'Iowa U.S. District Court');
INSERT INTO Source VALUES (168,'Michigan U.S. District Court');
INSERT INTO Source VALUES (169,'Mississippi U.S. District Court');
INSERT INTO Source VALUES (170,'Missouri U.S. District Court');
INSERT INTO Source VALUES (171,'New Jersey Eastern U.S. District Court (East Jersey U.S. District Court)');
INSERT INTO Source VALUES (172,'New Jersey Western U.S. District Court (West Jersey U.S. District Court)');
INSERT INTO Source VALUES (173,'New York U.S. District Court');
INSERT INTO Source VALUES (174,'North Carolina U.S. District Court');
INSERT INTO Source VALUES (175,'Ohio U.S. District Court');
INSERT INTO Source VALUES (176,'Pennsylvania U.S. District Court');
INSERT INTO Source VALUES (177,'Tennessee U.S. District Court');
INSERT INTO Source VALUES (178,'Texas U.S. District Court');
INSERT INTO Source VALUES (179,'Virginia U.S. District Court');
INSERT INTO Source VALUES (180,'Norfolk U.S. District Court');
INSERT INTO Source VALUES (181,'Wisconsin U.S. District Court');
INSERT INTO Source VALUES (182,'Kentucky U.S. Distrcrict Court');
INSERT INTO Source VALUES (183,'New Jersey U.S. District Court');
INSERT INTO Source VALUES (184,'California U.S. District Court');
INSERT INTO Source VALUES (185,'Florida U.S. District Court');
INSERT INTO Source VALUES (186,'Arkansas U.S. District Court');
INSERT INTO Source VALUES (187,'District of Orleans U.S. District Court');
INSERT INTO Source VALUES (300,'State Supreme Court');
INSERT INTO Source VALUES (301,'State Appellate Court');
INSERT INTO Source VALUES (302,'State Trial Court');
INSERT INTO Source VALUES (400,'Eastern Circuit (of the United States)');
INSERT INTO Source VALUES (401,'Middle Circuit (of the United States)');
INSERT INTO Source VALUES (402,'Southern Circuit (of the United States)');
INSERT INTO Source VALUES (403,'Alabama U.S. Circuit Court for (all) District(s) of Alabama');
INSERT INTO Source VALUES (404,'Arkansas U.S. Circuit Court for (all) District(s) of Arkansas');
INSERT INTO Source VALUES (405,'California U.S. Circuit for (all) District(s) of California');
INSERT INTO Source VALUES (406,'Connecticut U.S. Circuit for the District of Connecticut');
INSERT INTO Source VALUES (407,'Delaware U.S. Circuit for the District of Delaware');
INSERT INTO Source VALUES (408,'Florida U.S. Circuit for (all) District(s) of Florida');
INSERT INTO Source VALUES (409,'Georgia U.S. Circuit for (all) District(s) of Georgia');
INSERT INTO Source VALUES (410,'Illinois U.S. Circuit for (all) District(s) of Illinois');
INSERT INTO Source VALUES (411,'Indiana U.S. Circuit for (all) District(s) of Indiana');
INSERT INTO Source VALUES (412,'Iowa U.S. Circuit for (all) District(s) of Iowa');
INSERT INTO Source VALUES (413,'Kansas U.S. Circuit for the District of Kansas');
INSERT INTO Source VALUES (414,'Kentucky U.S. Circuit for (all) District(s) of Kentucky');
INSERT INTO Source VALUES (415,'Louisiana U.S. Circuit for (all) District(s) of Louisiana');
INSERT INTO Source VALUES (416,'Maine U.S. Circuit for the District of Maine');
INSERT INTO Source VALUES (417,'Maryland U.S. Circuit for the District of Maryland');
INSERT INTO Source VALUES (418,'Massachusetts U.S. Circuit for the District of Massachusetts');
INSERT INTO Source VALUES (419,'Michigan U.S. Circuit for (all) District(s) of Michigan');
INSERT INTO Source VALUES (420,'Minnesota U.S. Circuit for the District of Minnesota');
INSERT INTO Source VALUES (421,'Mississippi U.S. Circuit for (all) District(s) of Mississippi');
INSERT INTO Source VALUES (422,'Missouri U.S. Circuit for (all) District(s) of Missouri');
INSERT INTO Source VALUES (423,'Nevada U.S. Circuit for the District of Nevada');
INSERT INTO Source VALUES (424,'New Hampshire U.S. Circuit for the District of New Hampshire');
INSERT INTO Source VALUES (425,'New Jersey U.S. Circuit for (all) District(s) of New Jersey');
INSERT INTO Source VALUES (426,'New York U.S. Circuit for (all) District(s) of New York');
INSERT INTO Source VALUES (427,'North Carolina U.S. Circuit for (all) District(s) of North Carolina');
INSERT INTO Source VALUES (428,'Ohio U.S. Circuit for (all) District(s) of Ohio');
INSERT INTO Source VALUES (429,'Oregon U.S. Circuit for the District of Oregon');
INSERT INTO Source VALUES (430,'Pennsylvania U.S. Circuit for (all) District(s) of Pennsylvania');
INSERT INTO Source VALUES (431,'Rhode Island U.S. Circuit for the District of Rhode Island');
INSERT INTO Source VALUES (432,'South Carolina U.S. Circuit for the District of South Carolina');
INSERT INTO Source VALUES (433,'Tennessee U.S. Circuit for (all) District(s) of Tennessee');
INSERT INTO Source VALUES (434,'Texas U.S. Circuit for (all) District(s) of Texas');
INSERT INTO Source VALUES (435,'Vermont U.S. Circuit for the District of Vermont');
INSERT INTO Source VALUES (436,'Virginia U.S. Circuit for (all) District(s) of Virginia');
INSERT INTO Source VALUES (437,'West Virginia U.S. Circuit for (all) District(s) of West Virginia');
INSERT INTO Source VALUES (438,'Wisconsin U.S. Circuit for (all) District(s) of Wisconsin');
INSERT INTO Source VALUES (439,'Wyoming U.S. Circuit for the District of Wyoming');
INSERT INTO Source VALUES (440,'Circuit Court of the District of Columbia');
INSERT INTO Source VALUES (441,'Nebraska U.S. Circuit for the District of Nebraska');
INSERT INTO Source VALUES (442,'Colorado U.S. Circuit for the District of Colorado');
INSERT INTO Source VALUES (443,'Washington U.S. Circuit for (all) District(s) of Washington');
INSERT INTO Source VALUES (444,'Idaho U.S. Circuit Court for (all) District(s) of Idaho');
INSERT INTO Source VALUES (445,'Montana U.S. Circuit Court for (all) District(s) of Montana');
INSERT INTO Source VALUES (446,'Utah U.S. Circuit Court for (all) District(s) of Utah');
INSERT INTO Source VALUES (447,'South Dakota U.S. Circuit Court for (all) District(s) of South Dakota');
INSERT INTO Source VALUES (448,'North Dakota U.S. Circuit Court for (all) District(s) of North Dakota');
INSERT INTO Source VALUES (449,'Oklahoma U.S. Circuit Court for (all) District(s) of Oklahoma');
INSERT INTO Source VALUES (601,'Court of Private Land Claims');


